services:
  rag-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: context_aware_rag_chatbot
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped